### ISSUE TITLE
Consider switching from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by nikonthethird** [arivera12/BlazorHistory#1]
System.Text.Json is included in Blazor because it is a dependency of [Microsoft.AspNetCore.Components.WebAssembly](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.WebAssembly/). Specifically [Microsoft.Extensions.Configuration.Json](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/).

This would remove the extra Newtonsoft.Json dependency at basically no cost.

**Comment by arivera12** [comment]
System.Text.Json is feature less compared to Newtonsoft.Json, take a look of all the things that aren't not supported yet by System.Text.Json. 

https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to

I don't think I would work on this since it would be a waste of time not giving support to some built-in .net datatypes that are not even supported already by System.Text.Json.

I will keep sticked to Newtonsoft.Json until Microsoft supports everything that is already supported by Newtonsoft.Json.
